name 'poise-go'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures poise-go'
long_description 'Installs/Configures poise-go'
version '0.1.0'
